apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/monitoring.yaml
  - namespaces/logging.yaml
  - namespaces/apps.yaml
  - namespaces/opensearch.yaml
  - argo-apps/monitoring-kube-prometheus-stack.yaml
  - argo-apps/logging-loki-stack.yaml
