apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falcon-logging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.2
    helm:
      releaseName: falcon-logging
      values: |
        fullnameOverride: falcon-logging
        loki:
          enabled: true
        promtail:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
