apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falcon-opensearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://opensearch-project.github.io/helm-charts
    chart: opensearch
    targetRevision: 2.28.0
    helm:
      releaseName: falcon-opensearch
      values: |
        replicas: 1
        minimumMasterNodes: 1
        persistence:
          enabled: false
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
  destination:
    server: https://kubernetes.default.svc
    namespace: opensearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
